export const SCENE_KEYS = {
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  MAIN_MENU_SCENE: 'MAIN_MENU_SCENE',
  GAME_SCENE: 'GAME_SCENE',
  UI_SCENE: 'UI_SCENE',
  GAME_OVER_SCENE: 'GAME_OVER_SCENE',
} as const;
