export const ENABLE_LOGGING = true;

export const PLAYER_SPEED = 80;

export const ENERMY_SPIDER_SPEED = 80;
export const ENERMY_SPIDER_CHANGE_DIRECTION_DELAY_MIN = 500;
export const ENERMY_SPIDER_CHANGE_DIRECTION_DELAY_MAX = 1500;
export const ENERMY_SPIDER_CHANGE_DIRECTION_DELAY_WAIT = 200;
